apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-config
  namespace: spodoy-dev
data:
  SERVER_URL: "http://127.0.0.1:3000"
  CLOUDANT_URL: "https://b0bcb5f7-f822-40ae-9c5d-22eaca54a65a-bluemix.cloudantnosqldb.appdomain.cloud/"
  CLOUDANT_DB_NAME: "cheese-storage"
