apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-deployment
  namespace: spodoy-dev
  labels:
    app: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: todo-db-nextjs
        image: spodo/todo-db:latest
        ports:
        - containerPort: 3000
          name: todo
        env:
          - name: CLOUDANT_URL
            valueFrom:
              configMapKeyRef:
                name: todo-config
                key: CLOUDANT_URL
          - name: CLOUDANT_DB_NAME
            valueFrom:
              configMapKeyRef:
                name: todo-config
                key: CLOUDANT_DB_NAME
          - name: CLOUDANT_APIKEY
            valueFrom:
              secretKeyRef:
                name: todo-db-secret
                key: apikey